# Generated by Django 5.2.10 on 2026-02-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_learning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("div_name", models.CharField(max_length=25)),
            ],
        ),
    ]
