# Generated by Django 5.2.10 on 2026-02-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_learning", "0003_division_in_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="priority",
            field=models.CharField(
                choices=[("H", "High"), ("M", "Medium"), ("L", "Low")],
                default="M",
                max_length=1,
                verbose_name="Learning Priorities",
            ),
        ),
    ]
