# Generated by Django 5.2.10 on 2026-02-09 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_learning", "0004_employee_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="reg_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Registration Date"
            ),
        ),
    ]
